Repository so2niko-students/what-f-test-b, pull requests merged in 2020-11, with the labels that each got.

#4 Add Groups Api
  index.js
  mocks/groups.json
Labels: Ready to code review, Ready to merge

#5 Creating an account
  README.md
  index.js
  mocks/users.json
Labels: Ready to code review, Ready to merge, enhancement

#6 Added Courses API
  README.md
  index.js
  mocks/courses.json
Labels: Ready to code review, Ready to merge, enhancement

#3 Added authentification
  index.js
Labels: Ready to code review, Ready to merge, enhancement

#7 Added mentors API
  README.md
  index.js
  mocks/users.json
Labels: Ready to code review, Ready to merge, enhancement

#9 Add Lesson API
  index.js
  mocks/lessons.json
  mocks/students.json
Labels: Ready to code review, Ready to merge, enhancement

#10 Fixed mentor editing according to new endpoint
  index.js
  mocks/groups.json
  mocks/mentors.json
Labels: Ready to code review, bug

#8 Students API added
  index.js
Labels: enhancement
